const timezones = [
    {value: 'Europe/Moscow'},
    {value: 'Europe/Kaliningrad'},
    {value: 'Europe/Ulyanovsk'},
    {value: 'Europe/Minsk'},
    {value: 'Europe/Saratov'},
    {value: 'Europe/Volgograd'},
    {value: 'Europe/Samara'},
    {value: 'Europe/Simferopol'},
    {value: 'Asia/Chita'},
    {value: 'Asia/Krasnoyarsk'},
    {value: 'Asia/Omsk'},
    {value: 'Asia/Magadan'},
    {value: 'Asia/Sakhalin'},
    {value: 'Asia/Tomsk'},
    {value: 'Asia/Yekaterinburg'},
    {value: 'Asia/Irkutsk'},
    {value: 'Asia/Novokuznetsk'},
    {value: 'Asia/Srednekolymsk'},
    {value: 'Asia/Vladivostok'},
    {value: 'Asia/Anadyr'},
    {value: 'Asia/Kamchatka'},
    {value: 'Asia/Novosibirsk'},
    {value: 'Asia/Yakutsk'},
    {value: 'Asia/Barnaul'},
    {value: 'Asia/Barnaul'},
    {value: 'Asia/Barnaul'},
    {value: 'Asia/Barnaul'},
    {value: 'Asia/Barnaul'},
    {value: 'Asia/Barnaul'},
    {value: 'Asia/Barnaul'},
    
]

export default timezones;